//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EyeRef2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="user", Namespace="http://schemas.datacontract.org/2004/07/EyeWebService.UtilClasses")]
    [System.SerializableAttribute()]
    public partial class user : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EyeRef2.Address[] addressListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string genderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userTypeIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EyeRef2.Address[] addressList {
            get {
                return this.addressListField;
            }
            set {
                if ((object.ReferenceEquals(this.addressListField, value) != true)) {
                    this.addressListField = value;
                    this.RaisePropertyChanged("addressList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dob {
            get {
                return this.dobField;
            }
            set {
                if ((object.ReferenceEquals(this.dobField, value) != true)) {
                    this.dobField = value;
                    this.RaisePropertyChanged("dob");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gender {
            get {
                return this.genderField;
            }
            set {
                if ((object.ReferenceEquals(this.genderField, value) != true)) {
                    this.genderField = value;
                    this.RaisePropertyChanged("gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginId {
            get {
                return this.loginIdField;
            }
            set {
                if ((object.ReferenceEquals(this.loginIdField, value) != true)) {
                    this.loginIdField = value;
                    this.RaisePropertyChanged("loginId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userId {
            get {
                return this.userIdField;
            }
            set {
                if ((this.userIdField.Equals(value) != true)) {
                    this.userIdField = value;
                    this.RaisePropertyChanged("userId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userTypeId {
            get {
                return this.userTypeIdField;
            }
            set {
                if ((this.userTypeIdField.Equals(value) != true)) {
                    this.userTypeIdField = value;
                    this.RaisePropertyChanged("userTypeId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/EyeWebService.UtilClasses")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string countryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stateNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string streetNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string zipcodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string addressType {
            get {
                return this.addressTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.addressTypeField, value) != true)) {
                    this.addressTypeField = value;
                    this.RaisePropertyChanged("addressType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string country {
            get {
                return this.countryField;
            }
            set {
                if ((object.ReferenceEquals(this.countryField, value) != true)) {
                    this.countryField = value;
                    this.RaisePropertyChanged("country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phoneNo {
            get {
                return this.phoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneNoField, value) != true)) {
                    this.phoneNoField = value;
                    this.RaisePropertyChanged("phoneNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stateName {
            get {
                return this.stateNameField;
            }
            set {
                if ((object.ReferenceEquals(this.stateNameField, value) != true)) {
                    this.stateNameField = value;
                    this.RaisePropertyChanged("stateName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string streetName {
            get {
                return this.streetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.streetNameField, value) != true)) {
                    this.streetNameField = value;
                    this.RaisePropertyChanged("streetName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string zipcode {
            get {
                return this.zipcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.zipcodeField, value) != true)) {
                    this.zipcodeField = value;
                    this.RaisePropertyChanged("zipcode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Patient", Namespace="http://schemas.datacontract.org/2004/07/EyeWebService.UtilClasses")]
    [System.SerializableAttribute()]
    public partial class Patient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string genderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int parentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int patientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int providerIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dob {
            get {
                return this.dobField;
            }
            set {
                if ((object.ReferenceEquals(this.dobField, value) != true)) {
                    this.dobField = value;
                    this.RaisePropertyChanged("dob");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gender {
            get {
                return this.genderField;
            }
            set {
                if ((object.ReferenceEquals(this.genderField, value) != true)) {
                    this.genderField = value;
                    this.RaisePropertyChanged("gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int parentId {
            get {
                return this.parentIdField;
            }
            set {
                if ((this.parentIdField.Equals(value) != true)) {
                    this.parentIdField = value;
                    this.RaisePropertyChanged("parentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int patientId {
            get {
                return this.patientIdField;
            }
            set {
                if ((this.patientIdField.Equals(value) != true)) {
                    this.patientIdField = value;
                    this.RaisePropertyChanged("patientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int providerId {
            get {
                return this.providerIdField;
            }
            set {
                if ((this.providerIdField.Equals(value) != true)) {
                    this.providerIdField = value;
                    this.RaisePropertyChanged("providerId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Therapy", Namespace="http://schemas.datacontract.org/2004/07/EyeWebService.UtilClasses")]
    [System.SerializableAttribute()]
    public partial class Therapy : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string therapyDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int therapyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string therapyNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string therapyDescription {
            get {
                return this.therapyDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.therapyDescriptionField, value) != true)) {
                    this.therapyDescriptionField = value;
                    this.RaisePropertyChanged("therapyDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int therapyId {
            get {
                return this.therapyIdField;
            }
            set {
                if ((this.therapyIdField.Equals(value) != true)) {
                    this.therapyIdField = value;
                    this.RaisePropertyChanged("therapyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string therapyName {
            get {
                return this.therapyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.therapyNameField, value) != true)) {
                    this.therapyNameField = value;
                    this.RaisePropertyChanged("therapyName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Game", Namespace="http://schemas.datacontract.org/2004/07/EyeWebService.UtilClasses")]
    [System.SerializableAttribute()]
    public partial class Game : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gameDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int gameIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gameNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EyeRef2.Therapy therapyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gameDescription {
            get {
                return this.gameDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.gameDescriptionField, value) != true)) {
                    this.gameDescriptionField = value;
                    this.RaisePropertyChanged("gameDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int gameId {
            get {
                return this.gameIdField;
            }
            set {
                if ((this.gameIdField.Equals(value) != true)) {
                    this.gameIdField = value;
                    this.RaisePropertyChanged("gameId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gameName {
            get {
                return this.gameNameField;
            }
            set {
                if ((object.ReferenceEquals(this.gameNameField, value) != true)) {
                    this.gameNameField = value;
                    this.RaisePropertyChanged("gameName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EyeRef2.Therapy therapy {
            get {
                return this.therapyField;
            }
            set {
                if ((object.ReferenceEquals(this.therapyField, value) != true)) {
                    this.therapyField = value;
                    this.RaisePropertyChanged("therapy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientGameScore", Namespace="http://schemas.datacontract.org/2004/07/EyeWebService.UtilClasses")]
    [System.SerializableAttribute()]
    public partial class PatientGameScore : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EyeRef2.Game gameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EyeRef2.GameScore[] gameScoreListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int levelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int patientIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EyeRef2.Game game {
            get {
                return this.gameField;
            }
            set {
                if ((object.ReferenceEquals(this.gameField, value) != true)) {
                    this.gameField = value;
                    this.RaisePropertyChanged("game");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EyeRef2.GameScore[] gameScoreList {
            get {
                return this.gameScoreListField;
            }
            set {
                if ((object.ReferenceEquals(this.gameScoreListField, value) != true)) {
                    this.gameScoreListField = value;
                    this.RaisePropertyChanged("gameScoreList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int level {
            get {
                return this.levelField;
            }
            set {
                if ((this.levelField.Equals(value) != true)) {
                    this.levelField = value;
                    this.RaisePropertyChanged("level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int patientId {
            get {
                return this.patientIdField;
            }
            set {
                if ((this.patientIdField.Equals(value) != true)) {
                    this.patientIdField = value;
                    this.RaisePropertyChanged("patientId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameScore", Namespace="http://schemas.datacontract.org/2004/07/EyeWebService.UtilClasses")]
    [System.SerializableAttribute()]
    public partial class GameScore : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string datePlayedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan durationInMinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int scoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string datePlayed {
            get {
                return this.datePlayedField;
            }
            set {
                if ((object.ReferenceEquals(this.datePlayedField, value) != true)) {
                    this.datePlayedField = value;
                    this.RaisePropertyChanged("datePlayed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan durationInMin {
            get {
                return this.durationInMinField;
            }
            set {
                if ((this.durationInMinField.Equals(value) != true)) {
                    this.durationInMinField = value;
                    this.RaisePropertyChanged("durationInMin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int score {
            get {
                return this.scoreField;
            }
            set {
                if ((this.scoreField.Equals(value) != true)) {
                    this.scoreField = value;
                    this.RaisePropertyChanged("score");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientGames", Namespace="http://schemas.datacontract.org/2004/07/EyeWebService.UtilClasses")]
    [System.SerializableAttribute()]
    public partial class PatientGames : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EyeRef2.GameAssignment[] gameAssignmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int patientIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EyeRef2.GameAssignment[] gameAssignments {
            get {
                return this.gameAssignmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.gameAssignmentsField, value) != true)) {
                    this.gameAssignmentsField = value;
                    this.RaisePropertyChanged("gameAssignments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int patientId {
            get {
                return this.patientIdField;
            }
            set {
                if ((this.patientIdField.Equals(value) != true)) {
                    this.patientIdField = value;
                    this.RaisePropertyChanged("patientId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameAssignment", Namespace="http://schemas.datacontract.org/2004/07/EyeWebService.UtilClasses")]
    [System.SerializableAttribute()]
    public partial class GameAssignment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string endDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EyeRef2.Game gameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int levelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string startDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string endDate {
            get {
                return this.endDateField;
            }
            set {
                if ((object.ReferenceEquals(this.endDateField, value) != true)) {
                    this.endDateField = value;
                    this.RaisePropertyChanged("endDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EyeRef2.Game game {
            get {
                return this.gameField;
            }
            set {
                if ((object.ReferenceEquals(this.gameField, value) != true)) {
                    this.gameField = value;
                    this.RaisePropertyChanged("game");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int level {
            get {
                return this.levelField;
            }
            set {
                if ((this.levelField.Equals(value) != true)) {
                    this.levelField = value;
                    this.RaisePropertyChanged("level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string startDate {
            get {
                return this.startDateField;
            }
            set {
                if ((object.ReferenceEquals(this.startDateField, value) != true)) {
                    this.startDateField = value;
                    this.RaisePropertyChanged("startDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EyeRef2.IEyeWebService")]
    public interface IEyeWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEyeWebService/SetProfile", ReplyAction="http://tempuri.org/IEyeWebService/SetProfileResponse")]
        bool SetProfile(EyeRef2.user newUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEyeWebService/GetUserId", ReplyAction="http://tempuri.org/IEyeWebService/GetUserIdResponse")]
        int GetUserId(string loginId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEyeWebService/GetUserTypeId", ReplyAction="http://tempuri.org/IEyeWebService/GetUserTypeIdResponse")]
        int GetUserTypeId(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEyeWebService/ListChildrenProfile", ReplyAction="http://tempuri.org/IEyeWebService/ListChildrenProfileResponse")]
        EyeRef2.Patient[] ListChildrenProfile(int parentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEyeWebService/GetPatientProfile", ReplyAction="http://tempuri.org/IEyeWebService/GetPatientProfileResponse")]
        EyeRef2.Patient GetPatientProfile(int patientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEyeWebService/ListAllProviderProfile", ReplyAction="http://tempuri.org/IEyeWebService/ListAllProviderProfileResponse")]
        EyeRef2.user[] ListAllProviderProfile();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEyeWebService/SetChildProfile", ReplyAction="http://tempuri.org/IEyeWebService/SetChildProfileResponse")]
        EyeRef2.Patient SetChildProfile(EyeRef2.Patient newPatient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEyeWebService/ListPatientsProfile", ReplyAction="http://tempuri.org/IEyeWebService/ListPatientsProfileResponse")]
        EyeRef2.Patient[] ListPatientsProfile(int providerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEyeWebService/DeleteProfile", ReplyAction="http://tempuri.org/IEyeWebService/DeleteProfileResponse")]
        bool DeleteProfile(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEyeWebService/GetUserProfile", ReplyAction="http://tempuri.org/IEyeWebService/GetUserProfileResponse")]
        EyeRef2.user GetUserProfile(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEyeWebService/GetParentProfile", ReplyAction="http://tempuri.org/IEyeWebService/GetParentProfileResponse")]
        EyeRef2.user GetParentProfile(int childId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEyeWebService/GetProviderProfile", ReplyAction="http://tempuri.org/IEyeWebService/GetProviderProfileResponse")]
        EyeRef2.user GetProviderProfile(int patientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEyeWebService/CreateUpdateTherapy", ReplyAction="http://tempuri.org/IEyeWebService/CreateUpdateTherapyResponse")]
        bool CreateUpdateTherapy(EyeRef2.Therapy newTherapy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEyeWebService/CreateUpdateGame", ReplyAction="http://tempuri.org/IEyeWebService/CreateUpdateGameResponse")]
        EyeRef2.Game CreateUpdateGame(EyeRef2.Game newGame);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEyeWebService/ListAllTherapy", ReplyAction="http://tempuri.org/IEyeWebService/ListAllTherapyResponse")]
        EyeRef2.Therapy[] ListAllTherapy();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEyeWebService/ListAllGamesForTherapy", ReplyAction="http://tempuri.org/IEyeWebService/ListAllGamesForTherapyResponse")]
        EyeRef2.Game[] ListAllGamesForTherapy(int therapyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEyeWebService/DeleteGame", ReplyAction="http://tempuri.org/IEyeWebService/DeleteGameResponse")]
        bool DeleteGame(int gameId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEyeWebService/DeleteTherapy", ReplyAction="http://tempuri.org/IEyeWebService/DeleteTherapyResponse")]
        bool DeleteTherapy(int therapyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEyeWebService/ListGameScoresForPatient", ReplyAction="http://tempuri.org/IEyeWebService/ListGameScoresForPatientResponse")]
        EyeRef2.PatientGameScore ListGameScoresForPatient(EyeRef2.PatientGameScore patientGameScore);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEyeWebService/ListGameAssignment", ReplyAction="http://tempuri.org/IEyeWebService/ListGameAssignmentResponse")]
        EyeRef2.PatientGames ListGameAssignment(int patientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEyeWebService/SetGameScoresForPatient", ReplyAction="http://tempuri.org/IEyeWebService/SetGameScoresForPatientResponse")]
        EyeRef2.PatientGameScore SetGameScoresForPatient(EyeRef2.PatientGameScore patientGameScore);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEyeWebService/SetGameAssignment", ReplyAction="http://tempuri.org/IEyeWebService/SetGameAssignmentResponse")]
        bool SetGameAssignment(EyeRef2.PatientGames patientGames);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEyeWebService/DeleteGameAssignment", ReplyAction="http://tempuri.org/IEyeWebService/DeleteGameAssignmentResponse")]
        bool DeleteGameAssignment(EyeRef2.PatientGames patientGames);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEyeWebServiceChannel : EyeRef2.IEyeWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EyeWebServiceClient : System.ServiceModel.ClientBase<EyeRef2.IEyeWebService>, EyeRef2.IEyeWebService {
        
        public EyeWebServiceClient() {
        }
        
        public EyeWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EyeWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EyeWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EyeWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SetProfile(EyeRef2.user newUser) {
            return base.Channel.SetProfile(newUser);
        }
        
        public int GetUserId(string loginId) {
            return base.Channel.GetUserId(loginId);
        }
        
        public int GetUserTypeId(int userId) {
            return base.Channel.GetUserTypeId(userId);
        }
        
        public EyeRef2.Patient[] ListChildrenProfile(int parentId) {
            return base.Channel.ListChildrenProfile(parentId);
        }
        
        public EyeRef2.Patient GetPatientProfile(int patientId) {
            return base.Channel.GetPatientProfile(patientId);
        }
        
        public EyeRef2.user[] ListAllProviderProfile() {
            return base.Channel.ListAllProviderProfile();
        }
        
        public EyeRef2.Patient SetChildProfile(EyeRef2.Patient newPatient) {
            return base.Channel.SetChildProfile(newPatient);
        }
        
        public EyeRef2.Patient[] ListPatientsProfile(int providerId) {
            return base.Channel.ListPatientsProfile(providerId);
        }
        
        public bool DeleteProfile(int userId) {
            return base.Channel.DeleteProfile(userId);
        }
        
        public EyeRef2.user GetUserProfile(int userId) {
            return base.Channel.GetUserProfile(userId);
        }
        
        public EyeRef2.user GetParentProfile(int childId) {
            return base.Channel.GetParentProfile(childId);
        }
        
        public EyeRef2.user GetProviderProfile(int patientId) {
            return base.Channel.GetProviderProfile(patientId);
        }
        
        public bool CreateUpdateTherapy(EyeRef2.Therapy newTherapy) {
            return base.Channel.CreateUpdateTherapy(newTherapy);
        }
        
        public EyeRef2.Game CreateUpdateGame(EyeRef2.Game newGame) {
            return base.Channel.CreateUpdateGame(newGame);
        }
        
        public EyeRef2.Therapy[] ListAllTherapy() {
            return base.Channel.ListAllTherapy();
        }
        
        public EyeRef2.Game[] ListAllGamesForTherapy(int therapyId) {
            return base.Channel.ListAllGamesForTherapy(therapyId);
        }
        
        public bool DeleteGame(int gameId) {
            return base.Channel.DeleteGame(gameId);
        }
        
        public bool DeleteTherapy(int therapyId) {
            return base.Channel.DeleteTherapy(therapyId);
        }
        
        public EyeRef2.PatientGameScore ListGameScoresForPatient(EyeRef2.PatientGameScore patientGameScore) {
            return base.Channel.ListGameScoresForPatient(patientGameScore);
        }
        
        public EyeRef2.PatientGames ListGameAssignment(int patientId) {
            return base.Channel.ListGameAssignment(patientId);
        }
        
        public EyeRef2.PatientGameScore SetGameScoresForPatient(EyeRef2.PatientGameScore patientGameScore) {
            return base.Channel.SetGameScoresForPatient(patientGameScore);
        }
        
        public bool SetGameAssignment(EyeRef2.PatientGames patientGames) {
            return base.Channel.SetGameAssignment(patientGames);
        }
        
        public bool DeleteGameAssignment(EyeRef2.PatientGames patientGames) {
            return base.Channel.DeleteGameAssignment(patientGames);
        }
    }
}
